version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - mediaManagerNetwork

  frontend:
    build:
      context: ./app
    ports:
      - "3001:3001"
    networks:
      - mediaManagerNetwork
    depends_on:
      - backend

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mediaManagerNetwork

networks:
  mediaManagerNetwork:
